apiVersion: v1
kind: Namespace
metadata:
  name: calculator-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: calculator-example
  namespace: calculator-ns
  labels:
    app: calculator-example
spec:
  containers:
  - name: calculator-example
    image: jersondavidma/calculator-example:v1
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-example-service
  namespace: calculator-ns
spec:
  type: NodePort
  selector:
    app: calculator-example
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
