apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-example
  template:
    metadata:
      labels:
        app: calculator-example
    spec:
      containers:
      - name: calculator-example
        image: jersondavidma/calculator-example:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-example-service
spec:
  type: NodePort
  selector:
    app: calculator-example
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
